apiVersion: apps/v1
kind: Deployment
metadata:
  name: myuserapp
  namespace: userapp
  labels:
    app: myuserapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myuserapp
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8087"
        prometheus.io/path: "/metrics"
      labels:
        app: myuserapp
    spec:
      containers:
        - name: userappcont
          image: sauravnirala/usermanagement:v1
          ports:
            - containerPort: 8087
---
apiVersion: v1
kind: Service
metadata:
  name: myuserapp-service
  namespace: userapp
spec:
  selector:
    app: myuserapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8087
  type: LoadBalancer
